### ISSUE TITLE
plugin crash with error below

### ISSUE THREAD

**Issue by aleksei-bulgak** [hypoport/idea-dozer-plugin#1]
null
java.lang.NullPointerException
    at de.hypoport.plugins.dozer.model.FieldExpression.<init>(FieldExpression.java:119)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.parseExpression(FieldExpressionConverter.java:41)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:31)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:14)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:87)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:62)
    at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:50)
    at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:649)
    at de.hypoport.plugins.dozer.model.FieldDefinition$$EnhancerByCGLIB$$30a31e53.getValue(<generated>)
    at de.hypoport.plugins.dozer.DozerFileDescription$DozerAnnotator.annotate(DozerFileDescription.java:36)
    at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.runAnnotators(DomHighlightingHelperImpl.java:62)
    at com.intellij.util.xml.highlighting.MockAnnotatingDomInspection.checkDomElement(MockAnnotatingDomInspection.java:34)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:70)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
    at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:86)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:69)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
    at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:86)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:69)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
    at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:86)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:69)
    at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
    at com.intellij.util.xml.highlighting.DomElementsInspection.checkFileElement(DomElementsInspection.java:73)
    at com.intellij.util.xml.impl.DefaultDomAnnotator.runInspection(DefaultDomAnnotator.java:53)
    at com.intellij.util.xml.impl.DefaultDomAnnotator.runInspection(DefaultDomAnnotator.java:81)
    at com.intellij.util.xml.impl.DefaultDomAnnotator.annotate(DefaultDomAnnotator.java:74)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:160)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:397)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:400)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
    at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:746)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:400)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
    at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:318)
    at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:173)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:400)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:388)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:368)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:193)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

java.lang.NullPointerException
    at de.hypoport.plugins.dozer.model.FieldExpression.<init>(FieldExpression.java:119)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.parseExpression(FieldExpressionConverter.java:41)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:31)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:14)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:87)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:62)
    at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:50)
    at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:649)
    at de.hypoport.plugins.dozer.model.FieldDefinition$$EnhancerByCGLIB$$30a31e53.getValue(<generated>)
    at com.intellij.util.xml.impl.GenericDomValueReference.resolve(GenericDomValueReference.java:136)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection.a(DeprecatedClassUsageInspection.java:64)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection.access$000(DeprecatedClassUsageInspection.java:33)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection$1.visitXmlTag(DeprecatedClassUsageInspection.java:44)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1027)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:380)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:375)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

java.lang.NullPointerException
    at de.hypoport.plugins.dozer.model.FieldExpression.<init>(FieldExpression.java:119)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.parseExpression(FieldExpressionConverter.java:41)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:31)
    at de.hypoport.plugins.dozer.converter.FieldExpressionConverter.fromString(FieldExpressionConverter.java:14)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:87)
    at com.intellij.util.xml.impl.GetInvocation.a(GetInvocation.java:62)
    at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:50)
    at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:649)
    at de.hypoport.plugins.dozer.model.FieldDefinition$$EnhancerByCGLIB$$30a31e53.getValue(<generated>)
    at com.intellij.util.xml.impl.GenericDomValueReference.resolve(GenericDomValueReference.java:136)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection.a(DeprecatedClassUsageInspection.java:64)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection.access$000(DeprecatedClassUsageInspection.java:33)
    at com.intellij.codeInspection.xml.DeprecatedClassUsageInspection$1.visitXmlTag(DeprecatedClassUsageInspection.java:44)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1027)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:380)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:375)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by aleksei-bulgak** [comment]
![error-screen](https://cloud.githubusercontent.com/assets/1677410/3454596/916fc3da-01d3-11e4-8261-a9b8ff47cefd.png)

**Comment by gitsnaf** [comment]
Can you please provide some more information as the stack trace? Which version of IDEA are you using? A little testcase would be helpful.

**Comment by aleksei-bulgak** [comment]
I'm using  latest IDEA 13.1.3. 
I'm writing mapping between simple model classes and JAXB generated classes. Also I use Hibernate and Spring in my project.

**Comment by gitsnaf** [comment]
Can you provide a testcase or at least the dozer mapping file where the occurs?
Without such information we can hardly reproduce this error.

**Comment by aleksei-bulgak** [comment]
plugin crashes during IDEA start not during parsing something

**Comment by gitsnaf** [comment]
Ok, I'll take a look.

**Comment by aleksei-bulgak** [comment]
this is part of my xml mapping. may be it helps you 
https://onedrive.live.com/redir?resid=C48A066A5E1004CE!6792&authkey=!AIeKcK9OFNa06uQ&ithint=file%2c.xml

**Comment by gitsnaf** [comment]
Thanks for providing the xml file. As to the stack trace I think it has something to do with xml parsing. We have a lot of IDEA 13.1.3 installations here and none is crashing when opening an empty project.

**Comment by gitsnaf** [comment]
The xml file was very helpful. I could reproduce and fix the NPE. Change is committed and a new version of the plugin is already uploaded to the repository.

**Comment by gitsnaf** [comment]
Update is available via JetBrains plugin repository.
